scripts: Fix shellcheck errors

diff --git a/dotfiles/bin/cap b/dotfiles/bin/cap
--- a/dotfiles/bin/cap
+++ b/dotfiles/bin/cap
@@ -14,13 +14,13 @@ get-window-name() {
     local id="$1"
     local output
     output="$(xprop -id "${id}" WM_NAME)"
-    echo "$(expr match "${output}" '.*"\(.*\)"')"
+    # Sample output: `WM_NAME(STRING) = "emacs@yui"`
+    echo "${output:19:-1}"
 }
 
 main() {
     local mode="-u"
     local name
-    local opt
     local window
     local filename
 
@@ -38,10 +38,15 @@ main() {
             s)
                 mode="-s"
                 ;;
+            *)
+                echo "Error: Invalid flag: ${option}"
+                exit 1
         esac
     done
 
     sleep .1
+    # `scrot` expands the filename in its own shell
+    #shellcheck disable=SC2016
     filename=$(scrot "%FT%T.png" "${mode}" -e 'echo $f')
     mkdir -p "${SCREENSHOT_HOME}/${name}/"
     mv "${filename}" "${SCREENSHOT_HOME}/${name}/"
